---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
    - /bin/cp .env.local $DEPLOYPATH
